### ISSUE TITLE
Support roads with ref=*

### ISSUE THREAD

**Issue by blackboxlogic** [ltog/osmi-addresses#117]
Regarding:
https://github.com/ltog/osmi-addresses/blob/cdae6e10d809b10ff7ea456eee41922d90f87f48/osmi/FirstHandler.hpp#L122

I went looking for how you match `addr:street` to highways and was pleased that you use variations on the `name` tag like `official_name`. Consider _also_ including the `ref` tag which is ["common for roads"](https://wiki.openstreetmap.org/wiki/Key:ref) (like "US 1") and when a name would only be duplicating the information in the ref=* tag, then the [ref and noname=yes is appropriate](https://wiki.openstreetmap.org/wiki/Names#Name_is_the_name_only).

**Comment by blackboxlogic** [comment]
Also consider removing `name_1` since it is deprecated.

**Comment by blackboxlogic** [comment]
Would you consider a pull request on this if I made one?

**Comment by ltog** [comment]
@blackboxlogic : Do you have a source for `name_1` being deprecated?

@Nakaner , @woodpeck : What do you think?

**Comment by woodpeck** [comment]
https://wiki.openstreetmap.org/wiki/Names#Deprecated_tags says that number suffixes are deprecated. I think that it would make sense to drop name_1.

**Comment by Nakaner** [comment]
`name_1` comes from iD users using the raw tag editor in iD (not the presets). If a user added `name=something` and then adds `name=anything else` in a row below, the second `name` is changed to `name_1` automatically because keys are unique per OSM object. I think we should join the other editors (namely JOSM) which tell their users that they cannot use a key twice.

**Comment by blackboxlogic** [comment]
I'm still hoping for your consideration on  https://github.com/ltog/osmi-addresses/pull/119
-Alex
